# Generated by Django 2.1.7 on 2019-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20190109_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',), 'verbose_name': 'services', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
