# Generated by Django 2.0.7 on 2019-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20190217_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
